---
# handlers file for role-django-nginx-gunicorn
  - name: nginx start
    service:
      name: nginx
      state: started

  - name: nginx restart
    service:
      name: nginx
      state: restarted